from typing import Protocol

from .models import (
    CpeResult,
    Customer,
    IntentPrediction,
    OutageResult,
    RadioResult,
    Service,
    Ticket,
    UpstreamResult,
)


class TicketSystem(Protocol):
    def customer(self, customer_id: int) -> Customer | None: ...
    def services(self, customer_id: int) -> list[Service]: ...
    def tickets(self, customer_id: int) -> list[Ticket]: ...
    def categories(self) -> tuple[str, ...]: ...
    def create_ticket(self, customer_id: int, category: str, note: str, key: str) -> Ticket: ...
    def add_note(self, ticket_id: int, note: str, key: str) -> Ticket: ...
    def resolve(self, ticket_id: int, key: str) -> Ticket: ...


class NetworkProbe(Protocol):
    async def cpe(self, service: Service) -> CpeResult: ...
    async def radio(self, service: Service) -> RadioResult: ...
    async def upstream(self, service: Service) -> UpstreamResult: ...
    async def outage(self, service: Service) -> OutageResult: ...


class LanguageModel(Protocol):
    async def classify(self, message: str) -> IntentPrediction: ...
    async def rewrite(self, text: str, facts: dict[str, object]) -> str: ...


class MessageSender(Protocol):
    def read_and_typing(self, sender_id: str, message_id: str) -> None: ...

    def send(self, sender_id: str, message: str, key: str) -> None: ...
